<?php

namespace App\Services;

class PlaceTypeTranslator
{
    /**
     * Googleのカテゴリ英名（key）とユーザー向け日本語（value）のマッピングマスタ
     */
    private array $categories = [
        // 自動車
        'car_dealer' => '自動車ディーラー',
        'car_rental' => 'レンタカー',
        'car_repair' => '自動車整備・修理',
        'car_wash' => '洗車場',
        'ebike_charging_station' => '電動自転車充電スタンド',
        'electric_vehicle_charging_station' => '電気自動車（EV）充電スタンド',
        'gas_station' => 'ガソリンスタンド',
        'parking' => '駐車場',
        'parking_garage' => '立体駐車場 / 屋内駐車場',
        'parking_lot' => '駐車場（平地）',
        'rest_stop' => 'パーキングエリア / 道の駅',
        'tire_shop' => 'タイヤ専門店',
        'truck_dealer' => 'トラックディーラー',

        // ビジネス・企業
        'business_center' => 'ビジネスセンター',
        'corporate_office' => '企業オフィス / 本社',
        'coworking_space' => 'コワーキングスペース',
        'farm' => '農場 / 農園',
        'manufacturer' => '製造業者 / 工場',
        'ranch' => '牧場',
        'supplier' => 'サプライヤー / 卸売業者',
        'television_studio' => 'テレビスタジオ',

        // 文化
        'art_gallery' => 'アートギャラリー / 画廊',
        'art_museum' => '美術館',
        'art_studio' => 'アートスタジオ / 工房',
        'auditorium' => 'オーディトリアム / 公会堂 / 講堂',
        'castle' => '城',
        'cultural_landmark' => '文化的ランドマーク',
        'fountain' => '噴水',
        'historical_place' => '史跡 / 歴史的場所',
        'history_museum' => '歴史博物館',
        'monument' => '記念碑 / モニュメント',
        'museum' => '博物館',
        'performing_arts_theater' => '劇場 / 演劇ホール',
        'sculpture' => '彫刻',

        // 教育
        'academic_department' => '大学の学部・学科',
        'educational_institution' => '教育機関',
        'library' => '図書館',
        'preschool' => '幼稚園 / 保育園',
        'primary_school' => '小学校',
        'research_institute' => '研究所',
        'school' => '学校',
        'secondary_school' => '中学校 / 高校',
        'university' => '大学',

        // エンターテイメント / レクリエーション
        'adventure_sports_center' => 'アドベンチャースポーツセンター',
        'amphitheatre' => '野外劇場 / 円形劇場',
        'amusement_center' => 'アミューズメントセンター / ゲームセンター',
        'amusement_park' => '遊園地',
        'aquarium' => '水族館',
        'banquet_hall' => '宴会場 / バンケットホール',
        'barbecue_area' => 'バーベキュー場',
        'botanical_garden' => '植物園',
        'bowling_alley' => 'ボウリング場',
        'casino' => 'カジノ',
        'childrens_camp' => '子供向けキャンプ場',
        'city_park' => '都市公園',
        'comedy_club' => 'コメディクラブ',
        'community_center' => '公民館 / コミュニティセンター',
        'concert_hall' => 'コンサートホール',
        'convention_center' => 'コンベンションセンター / 国際会議場',
        'cultural_center' => '文化センター',
        'cycling_park' => 'サイクリングパーク',
        'dance_hall' => 'ダンスホール',
        'dog_park' => 'ドッグラン / ドッグパーク',
        'event_venue' => 'イベント会場',
        'ferris_wheel' => '観覧車',
        'garden' => '庭園 / 庭',
        'go_karting_venue' => 'ゴーカート場',
        'hiking_area' => 'ハイキングエリア',
        'historical_landmark' => '歴史的建造物 / ランドマーク',
        'indoor_playground' => '屋内プレイルーム / キッズスペース',
        'internet_cafe' => 'インターネットカフェ',
        'karaoke' => 'カラオケ',
        'live_music_venue' => 'ライブハウス',
        'marina' => 'マリーナ（ヨット乗り場）',
        'miniature_golf_course' => 'ミニゴルフ場 / パターゴルフ場',
        'movie_rental' => 'レンタルビデオ店',
        'movie_theater' => '映画館',
        'national_park' => '国立公園',
        'night_club' => 'ナイトクラブ',
        'observation_deck' => '展望台',
        'off_roading_area' => 'オフロード走行エリア',
        'opera_house' => 'オペラハウス',
        'paintball_center' => 'ペイントボールセンター',
        'park' => '公園',
        'philharmonic_hall' => 'フィルハーモニーホール',
        'picnic_ground' => 'ピクニック場',
        'planetarium' => 'プラネタリウム',
        'plaza' => '広場 / プラザ',
        'roller_coaster' => 'ジェットコースター',
        'skateboard_park' => 'スケートボードパーク',
        'state_park' => '州立公園',
        'tourist_attraction' => '観光名所',
        'video_arcade' => 'ゲームセンター',
        'vineyard' => 'ブドウ園 / ワイン用のブドウ畑',
        'visitor_center' => 'ビジターセンター',
        'water_park' => 'ウォーターパーク / プール施設',
        'wedding_venue' => '結婚式場',
        'wildlife_park' => 'サファリパーク / 野生動物公園',
        'wildlife_refuge' => '野生動物保護区',
        'zoo' => '動物園',

        // 施設
        'public_bath' => '公衆浴場 / 銭湯',
        'public_bathroom' => '公衆トイレ',
        'stable' => '馬小屋 / 厩舎',

        // 金融
        'accounting' => '会計事務所',
        'atm' => 'ATM（現金自動預払機）',
        'bank' => '銀行',

        // フード、ドリンク
        'acai_shop' => 'アサイー専門店',
        'afghani_restaurant' => 'アフガニスタン料理店',
        'african_restaurant' => 'アフリカ料理店',
        'american_restaurant' => 'アメリカ料理店',
        'argentinian_restaurant' => 'アルゼンチン料理店',
        'asian_fusion_restaurant' => 'アジアンフュージョン（創作アジア料理）店',
        'asian_restaurant' => 'アジア料理店',
        'australian_restaurant' => 'オーストラリア料理店',
        'austrian_restaurant' => 'オーストリア料理店',
        'bagel_shop' => 'ベーグル店',
        'bakery' => 'パン屋 / ベーカリー',
        'bangladeshi_restaurant' => 'バングラデシュ料理店',
        'bar' => 'バー',
        'bar_and_grill' => 'バー＆グリル',
        'barbecue_restaurant' => 'バーベキュー料理店',
        'basque_restaurant' => 'バスク料理店',
        'bavarian_restaurant' => 'バイエルン料理店',
        'beer_garden' => 'ビアガーデン',
        'belgian_restaurant' => 'ベルギー料理店',
        'bistro' => 'ビストロ',
        'brazilian_restaurant' => 'ブラジル料理店',
        'breakfast_restaurant' => '朝食専門店',
        'brewery' => 'ビール醸造所',
        'brewpub' => 'ブリューパブ（醸造所併設のパブ）',
        'british_restaurant' => 'イギリス料理店',
        'brunch_restaurant' => 'ブランチレストラン',
        'buffet_restaurant' => 'ビュッフェ / 食べ放題レストラン',
        'burmese_restaurant' => 'ビルマ（ミャンマー）料理店',
        'burrito_restaurant' => 'ブリトー専門店',
        'cafe' => 'カフェ',
        'cafeteria' => 'カフェテリア / 食堂',
        'cajun_restaurant' => 'ケイジャン料理店',
        'cake_shop' => 'ケーキ屋',
        'californian_restaurant' => 'カリフォルニア料理店',
        'cambodian_restaurant' => 'カンボジア料理店',
        'candy_store' => 'キャンディ・お菓子店',
        'cantonese_restaurant' => '広東料理店',
        'caribbean_restaurant' => 'カリブ料理店',
        'cat_cafe' => '猫カフェ',
        'chicken_restaurant' => 'チキン料理店',
        'chicken_wings_restaurant' => 'バッファローチキンウィング（手羽先）専門店',
        'chilean_restaurant' => 'チリ料理店',
        'chinese_noodle_restaurant' => '中華麺専門店',
        'chinese_restaurant' => '中華料理店',
        'chocolate_factory' => 'チョコレート工場',
        'chocolate_shop' => 'チョコレート専門店',
        'cocktail_bar' => 'カクテルバー',
        'coffee_roastery' => 'コーヒー焙煎所',
        'coffee_shop' => 'コーヒーショップ',
        'coffee_stand' => 'コーヒースタンド',
        'colombian_restaurant' => 'コロンビア料理店',
        'confectionery' => '菓子店',
        'croatian_restaurant' => 'クロアチア料理店',
        'cuban_restaurant' => 'キューバ料理店',
        'czech_restaurant' => 'チェコ料理店',
        'danish_restaurant' => 'デンマーク料理店',
        'deli' => 'デリカテッセン / 惣菜店',
        'dessert_restaurant' => 'デザートレストラン',
        'dessert_shop' => 'デザートショップ / スイーツ店',
        'dim_sum_restaurant' => '点心専門店 / 飲茶',
        'diner' => 'ダイナー（アメリカ風食堂）',
        'dog_cafe' => 'ドッグカフェ',
        'donut_shop' => 'ドーナツ店',
        'dumpling_restaurant' => '餃子・点心専門店',
        'dutch_restaurant' => 'オランダ料理店',
        'eastern_european_restaurant' => '東欧料理店',
        'ethiopian_restaurant' => 'エチオピア料理店',
        'european_restaurant' => 'ヨーロッパ料理店',
        'falafel_restaurant' => 'ファラフェル専門店',
        'family_restaurant' => 'ファミリーレストラン',
        'fast_food_restaurant' => 'ファストフード店',
        'filipino_restaurant' => 'フィリピン料理店',
        'fine_dining_restaurant' => '高級レストラン / ファインダイニング',
        'fish_and_chips_restaurant' => 'フィッシュ・アンド・チップス専門店',
        'fondue_restaurant' => 'フォンデュ料理店',
        'food_court' => 'フードコート',
        'french_restaurant' => 'フランス料理店',
        'fusion_restaurant' => 'フュージョン（創作）料理店',
        'gastropub' => 'ガストロパブ（料理にこだわったパブ）',
        'german_restaurant' => 'ドイツ料理店',
        'greek_restaurant' => 'ギリシャ料理店',
        'gyro_restaurant' => 'ギロピタ（ギリシャ風ラップサンド）専門店',
        'halal_restaurant' => 'ハラール料理店',
        'hamburger_restaurant' => 'ハンバーガー店',
        'hawaiian_restaurant' => 'ハワイ料理店',
        'hookah_bar' => 'シーシャバー（水タバコ）',
        'hot_dog_restaurant' => 'ホットドッグ専門店',
        'hot_dog_stand' => 'ホットドッグスタンド（屋台）',
        'hot_pot_restaurant' => '火鍋・鍋料理専門店',
        'hungarian_restaurant' => 'ハンガリー料理店',
        'ice_cream_shop' => 'アイスクリーム店',
        'indian_restaurant' => 'インド料理店',
        'indonesian_restaurant' => 'インドネシア料理店',
        'irish_pub' => 'アイリッシュパブ',
        'irish_restaurant' => 'アイルランド料理店',
        'israeli_restaurant' => 'イスラエル料理店',
        'italian_restaurant' => 'イタリア料理店',
        'japanese_curry_restaurant' => 'カレー専門店（日本式）',
        'japanese_izakaya_restaurant' => '居酒屋',
        'japanese_restaurant' => '日本料理・和食店',
        'juice_shop' => 'ジューススタンド / ジュース専門店',
        'kebab_shop' => 'ケバブ店',
        'korean_barbecue_restaurant' => '韓国式焼肉店',
        'korean_restaurant' => '韓国料理店',
        'latin_american_restaurant' => '中南米（ラテンアメリカ）料理店',
        'lebanese_restaurant' => 'レバノン料理店',
        'lounge_bar' => 'ラウンジバー',
        'malaysian_restaurant' => 'マレーシア料理店',
        'meal_delivery' => '食事宅配サービス',
        'meal_takeaway' => 'テイクアウト専門店',
        'mediterranean_restaurant' => '地中海料理店',
        'mexican_restaurant' => 'メキシコ料理店',
        'middle_eastern_restaurant' => '中東料理店',
        'mongolian_barbecue_restaurant' => 'モンゴリアンバーベキュー店',
        'moroccan_restaurant' => 'モロッコ料理店',
        'noodle_shop' => '麺類専門店（ラーメン、うどん、そば等）',
        'north_indian_restaurant' => '北インド料理店',
        'oyster_bar_restaurant' => 'オイスターバー',
        'pakistani_restaurant' => 'パキスタン料理店',
        'pastry_shop' => 'ペストリーショップ / 洋菓子店',
        'persian_restaurant' => 'ペルシャ料理店',
        'peruvian_restaurant' => 'ペルー料理店',
        'pizza_delivery' => 'ピザデリバリー',
        'pizza_restaurant' => 'ピザ屋 / ピッツェリア',
        'polish_restaurant' => 'ポーランド料理店',
        'portuguese_restaurant' => 'ポルトガル料理店',
        'pub' => 'パブ',
        'ramen_restaurant' => 'ラーメン店',
        'restaurant' => 'レストラン / 飲食店',
        'romanian_restaurant' => 'ルーマニア料理店',
        'russian_restaurant' => 'ロシア料理店',
        'salad_shop' => 'サラダ専門店',
        'sandwich_shop' => 'サンドイッチ店',
        'scandinavian_restaurant' => 'スカンジナビア（北欧）料理店',
        'seafood_restaurant' => 'シーフード料理店',
        'shawarma_restaurant' => 'シャワルマ（中東風ラップサンド）専門店',
        'snack_bar' => 'スナックバー / 軽食店',
        'soul_food_restaurant' => 'ソウルフード（アメリカ南部伝統料理）店',
        'soup_restaurant' => 'スープ専門店',
        'south_american_restaurant' => '南米料理店',
        'south_indian_restaurant' => '南インド料理店',
        'southwestern_us_restaurant' => 'アメリカ南西部料理店',
        'spanish_restaurant' => 'スペイン料理店',
        'sports_bar' => 'スポーツバー',
        'sri_lankan_restaurant' => 'スリランカ料理店',
        'steak_house' => 'ステーキハウス',
        'sushi_restaurant' => '寿司店',
        'swiss_restaurant' => 'スイス料理店',
        'taco_restaurant' => 'タコス専門店',
        'taiwanese_restaurant' => '台湾料理店',
        'tapas_restaurant' => 'タパスバル / スペイン小皿料理店',
        'tea_house' => 'ティーハウス / 茶館',
        'tex_mex_restaurant' => 'テクス・メクス（テキサス風メキシコ）料理店',
        'thai_restaurant' => 'タイ料理店',
        'tibetan_restaurant' => 'チベット料理店',
        'tonkatsu_restaurant' => 'とんかつ店',
        'turkish_restaurant' => 'トルコ料理店',
        'ukrainian_restaurant' => 'ウクライナ料理店',
        'vegan_restaurant' => 'ヴィーガンレストラン',
        'vegetarian_restaurant' => 'ベジタリアンレストラン',
        'vietnamese_restaurant' => 'ベトナム料理店',
        'western_restaurant' => '洋食店',
        'wine_bar' => 'ワインバー',
        'winery' => 'ワイナリー（ワイン醸造所）',
        'yakiniku_restaurant' => '焼肉店',
        'yakitori_restaurant' => '焼き鳥店',

        // 地理的エリア
        'administrative_area_level_1' => '第一級行政区画（都道府県）',
        'administrative_area_level_2' => '第二級行政区画（郡・振興局など）',
        'country' => '国',
        'locality' => '市町村 / 地域',
        'postal_code' => '郵便番号',
        'school_district' => '学区',

        // 政府機関
        'city_hall' => '市役所 / 区役所',
        'courthouse' => '裁判所',
        'embassy' => '大使館',
        'fire_station' => '消防署',
        'government_office' => '政府機関 / 官公庁',
        'local_government_office' => '地方自治体オフィス',
        'neighborhood_police_station' => '交番',
        'police' => '警察署',
        'post_office' => '郵便局',

        // 健康とウェルネス
        'chiropractor' => 'カイロプラクティック',
        'dental_clinic' => '歯科医院',
        'dentist' => '歯医者',
        'doctor' => '医師 / 診療所',
        'drugstore' => 'ドラッグストア',
        'general_hospital' => '総合病院',
        'hospital' => '病院',
        'massage' => 'マッサージ店',
        'massage_spa' => 'マッサージスパ',
        'medical_center' => 'メディカルセンター',
        'medical_clinic' => 'クリニック / 診療所',
        'medical_lab' => '医療検査機関',
        'pharmacy' => '調剤薬局 / 薬局',
        'physiotherapist' => '理学療法士 / 整体院',
        'sauna' => 'サウナ',
        'skin_care_clinic' => 'スキンケアクリニック / 美容皮膚科',
        'spa' => 'スパ',
        'tanning_studio' => '日焼けサロン',
        'wellness_center' => 'ウェルネスセンター',
        'yoga_studio' => 'ヨガスタジオ',

        // 住宅
        'apartment_building' => 'アパート / マンション（単棟）',
        'apartment_complex' => 'アパート・マンション団地 / 集合住宅群',
        'condominium_complex' => '分譲マンション一棟・団地',
        'housing_complex' => '集合住宅 / 団地',

        // 宿泊施設
        'bed_and_breakfast' => 'B&B（朝食付き民宿）',
        'budget_japanese_inn' => '格安旅館 / 民宿',
        'campground' => 'キャンプ場',
        'camping_cabin' => 'キャンプ用コテージ / キャビン',
        'cottage' => 'コテージ',
        'extended_stay_hotel' => '長期滞在型ホテル',
        'farmstay' => 'ファームステイ / 農場宿泊',
        'guest_house' => 'ゲストハウス',
        'hostel' => 'ホステル',
        'hotel' => 'ホテル',
        'inn' => 'イン / 宿屋',
        'japanese_inn' => '旅館',
        'lodging' => '宿泊施設（全般）',
        'mobile_home_park' => 'モバイルホーム（トレーラーハウス）パーク',
        'motel' => 'モーテル',
        'private_guest_room' => '民泊の個室 / プライベートルーム',
        'resort_hotel' => 'リゾートホテル',
        'rv_park' => 'RVパーク（キャンピングカー用駐車場）',

        // 自然地物
        'beach' => 'ビーチ / 海岸',
        'island' => '島',
        'lake' => '湖',
        'mountain_peak' => '山頂 / ピーク',
        'nature_preserve' => '自然保護区',
        'river' => '川',
        'scenic_spot' => '景勝地 / ビューポイント',
        'woods' => '森 / 林',

        // 礼拝所
        'buddhist_temple' => '仏教寺院 / お寺',
        'church' => '教会',
        'hindu_temple' => 'ヒンドゥー教寺院',
        'mosque' => 'モスク',
        'shinto_shrine' => '神社',
        'synagogue' => 'シナゴーグ（ユダヤ教礼拝所）',

        // サービス
        'aircraft_rental_service' => '航空機レンタルサービス',
        'association_or_organization' => '協会 / 団体',
        'astrologer' => '占星術師 / 占い',
        'barber_shop' => '理髪店 / 床屋',
        'beautician' => '美容家 / エステティシャン',
        'beauty_salon' => '美容院 / エステサロン',
        'body_art_service' => 'ボディエステ / タトゥー・ボディピアススタジオ',
        'catering_service' => 'ケータリングサービス',
        'cemetery' => '墓地 / 霊園',
        'chauffeur_service' => 'お抱え運転手サービス / 送迎サービス',
        'child_care_agency' => '託児エージェンシー / 保育サービス',
        'consultant' => 'コンサルタント',
        'courier_service' => '宅配便 / クーリエサービス',
        'electrician' => '電気工事業者',
        'employment_agency' => '人材紹介会社 / 派遣会社',
        'florist' => '花屋',
        'food_delivery' => 'フードデリバリーサービス',
        'foot_care' => 'フットケアサロン',
        'funeral_home' => '葬儀場',
        'hair_care' => 'ヘアケア専門店',
        'hair_salon' => 'ヘアサロン / 美容室',
        'insurance_agency' => '保険代理店',
        'laundry' => 'クリーニング店 / コインランドリー',
        'lawyer' => '弁護士 / 法律事務所',
        'locksmith' => '鍵屋',
        'makeup_artist' => 'メイクアップアーティスト',
        'marketing_consultant' => 'マーケティングコンサルタント',
        'moving_company' => '引越し業者',
        'nail_salon' => 'ネイルサロン',
        'non_profit_organization' => 'NPO / 非営利団体',
        'painter' => '塗装業者',
        'pet_boarding_service' => 'ペットホテル',
        'pet_care' => 'ペットケアサービス',
        'plumber' => '配管工事業者',
        'psychic' => '霊能者 / 占い師',
        'real_estate_agency' => '不動産会社',
        'roofing_contractor' => '屋根工事業者',
        'service' => 'サービス業（全般）',
        'shipping_service' => '配送サービス',
        'storage' => '貸し倉庫 / トランクールーム',
        'summer_camp_organizer' => 'サマーキャンプ主催者',
        'tailor' => '仕立て屋 / テーラー',
        'telecommunications_service_provider' => '電気通信事業者（携帯キャリアなど）',
        'tour_agency' => 'ツアー会社',
        'tourist_information_center' => '観光案内所',
        'travel_agency' => '旅行会社',
        'veterinary_care' => '獣医 / 動物病院',

        // ショッピング
        'asian_grocery_store' => 'アジア系食料品店',
        'auto_parts_store' => '自動車部品店',
        'bicycle_store' => '自転車店',
        'book_store' => '書店 / 本屋',
        'building_materials_store' => '建築資材店',
        'butcher_shop' => '精肉店 / お肉屋さん',
        'cell_phone_store' => '携帯ショップ',
        'clothing_store' => '衣料品店 / 服屋',
        'convenience_store' => 'コンビニエンスストア',
        'cosmetics_store' => '化粧品店',
        'department_store' => '百貨店 / デパート',
        'discount_store' => 'ディスカウントストア',
        'discount_supermarket' => '格安スーパー / ディスカウントスーパー',
        'electronics_store' => '家電量販店 / 電気屋',
        'farmers_market' => 'ファーマーズマーケット / 直売所',
        'flea_market' => 'フリーマーケット',
        'food_store' => '食料品店',
        'furniture_store' => '家具店',
        'garden_center' => '園芸店 / ガーデンセンター',
        'general_store' => '雑貨屋 / よろず屋',
        'gift_shop' => 'ギフトショップ / お土産屋',
        'grocery_store' => '食料品店 / スーパー',
        'hardware_store' => '金物店 / ホームセンター',
        'health_food_store' => '健康食品店',
        'home_goods_store' => 'ホームグッズ店 / インテリア雑貨店',
        'home_improvement_store' => 'ホームセンター',
        'hypermarket' => 'ハイパーマーケット（超大型スーパー）',
        'jewelry_store' => 'ジュエリーショップ / 宝石店',
        'liquor_store' => '酒屋',
        'market' => '市場',
        'pet_store' => 'ペットショップ',
        'shoe_store' => '靴屋',
        'shopping_mall' => 'ショッピングモール',
        'sporting_goods_store' => 'スポーツ用品店',
        'sportswear_store' => 'スポーツウェア専門店',
        'store' => '店舗 / ショップ',
        'supermarket' => 'スーパーマーケット',
        'tea_store' => '茶葉専門店',
        'thrift_store' => 'リサイクルショップ / 古着屋',
        'toy_store' => 'おもちゃ屋',
        'warehouse_store' => '倉庫型割引店（コストコなど）',
        'wholesaler' => '卸売業者',
        'womens_clothing_store' => '婦人服店',

        // スポーツ
        'arena' => 'アリーナ / 競技場',
        'athletic_field' => '運動場 / グラウンド',
        'fishing_charter' => '貸切釣り船',
        'fishing_pier' => '釣り桟橋',
        'fishing_pond' => '釣り堀',
        'fitness_center' => 'フィットネスセンター',
        'golf_course' => 'ゴルフ場',
        'gym' => 'ジム / 体育館',
        'ice_skating_rink' => 'アイススケートリンク',
        'indoor_golf_course' => 'インドアゴルフ練習場',
        'playground' => '遊び場 / 公園の遊具エリア',
        'race_course' => 'レースコース / 競馬場 / 競輪場',
        'ski_resort' => 'スキー場',
        'sports_activity_location' => 'スポーツ施設',
        'sports_club' => 'スポーツクラブ',
        'sports_coaching' => 'スポーツコーチング / 指導',
        'sports_complex' => '総合スポーツ施設',
        'sports_school' => 'スポーツスクール',
        'stadium' => 'スタジアム / 球場',
        'swimming_pool' => '水泳プール',
        'tennis_court' => 'テニスコート',

        // 交通
        'airport' => '空港',
        'airstrip' => '臨時滑走路 / 小型飛行場',
        'bike_sharing_station' => 'シェアサイクルポート',
        'bridge' => '橋',
        'bus_station' => 'バスターミナル',
        'bus_stop' => 'バス停',
        'ferry_service' => 'フェリー運航サービス',
        'ferry_terminal' => 'フェリーターミナル',
        'heliport' => 'ヘリポート',
        'international_airport' => '国際空港',
        'light_rail_station' => 'ライトレール（LRT・路面電車）駅',
        'park_and_ride' => 'パークアンドライド（駐車場付き駅）',
        'subway_station' => '地下鉄駅',
        'taxi_service' => 'タクシー配車サービス',
        'taxi_stand' => 'タクシー乗り場',
        'toll_station' => '料金所',
        'train_station' => '鉄道駅',
        'train_ticket_office' => '駅のみどりの窓口 / 切符売り場',
        'tram_stop' => '路面電車停留所',
        'transit_depot' => '車庫 / 交通デポ',
        'transit_station' => '乗り換え駅 / 交通ステーション',
        'transit_stop' => '交通停留所',
        'transportation_service' => '輸送・交通サービス',
        'truck_stop' => 'トラックストップ（大型車用PA）',

        // テーブルBの項目
        'administrative_area_level_3' => '市区町村',
        'administrative_area_level_4' => '町名・大字',
        'administrative_area_level_5' => '丁目',
        'administrative_area_level_6' => '行政区画（レベル6）',
        'administrative_area_level_7' => '行政区画（レベル7）',
        'archipelago' => '群島・列島',
        'colloquial_area' => '地域・エリア名',
        'continent' => '大陸',
        'establishment' => '店舗・施設',
        'finance' => '金融機関',
        'food' => '飲食店',
        'general_contractor' => '建設会社・ゼネコン',
        'geocode' => '位置情報（座標）',
        'health' => '医療・健康施設',
        'intersection' => '交差点名',
        'landmark' => 'ランドマーク・目印',
        'natural_feature' => '自然地形',
        'neighborhood' => '近隣地域・周辺地区',
        'place_of_worship' => '寺院・神社・教会',
        'plus_code' => 'プラスコード（位置コード）',
        'point_of_interest' => '周辺スポット・観光地',
        'political' => '行政区画',
        'postal_code_prefix' => '郵便番号（前半）',
        'postal_code_suffix' => '郵便番号（後半）',
        'postal_town' => '配送地区',
        'premise' => '敷地・建物名',
        'route' => '道路・ルート',
        'street_address' => '住所・番地',
        'sublocality' => '町域名',
        'sublocality_level_1' => '市区町村以下の区画（レベル1）',
        'sublocality_level_2' => '市区町村以下の区画（レベル2）',
        'sublocality_level_3' => '市区町村以下の区画（レベル3）',
        'sublocality_level_4' => '市区町村以下の区画（レベル4）',
        'sublocality_level_5' => '市区町村以下の区画（レベル5）',
        'subpremise' => '部屋番号・号室',
        'town_square' => '広場',
    ];

    /**
     * Googleのカテゴリ英名を日本語に変換する
     * * @param string|null $englishType Googleから返ってきた英名（例: 'amusement_park'）
     * @return string|null 日本語のカテゴリ名（マスタになければ元の英名、またはデフォルト値を返す）
     */
    public function translate(?string $englishType): string|null
    {
        if (empty($englishType)) {
            return null;
        }

        // マスタにあれば日本語を返し、なければ英名のまま（または「スポット」など）を返す
        return $this->categories[$englishType] ?? null;
    }
}
